#!/bin/sh
astyle --lineend=linux --pad-oper --indent=tab --remove-braces --pad-header --pad-comma --break-blocks --pad-oper --indent-switches *.cpp *.hpp *.c *.h autogeneratedBindings/*.cpp autogeneratedBindings/*.h
