/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class Fl_Lua_Choice
 *
 * This file has been generated by dub 2.2.4.
 */
#include "dub/dub.h"
#include <FL/Fl_Choice.H>
#include "cbHelper.h"
class Fl_Lua_Choice:public Fl_Choice{
using Fl_Choice::Fl_Choice;
public:
	struct cbInfo ci;
};


/** ~Fl_Lua_Choice()
 * 
 */
static int Fl_Lua_Choice__Fl_Lua_Choice(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "FLTK.Fl_Lua_Choice"));
    if (userdata->gc) {
      Fl_Lua_Choice *self = (Fl_Lua_Choice *)userdata->ptr;
	if(self->ci.cb) free(self->ci.cb);

      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** Cast (class_name)
 * 
 */
static int Fl_Lua_Choice__cast_(lua_State *L) {

  Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata_n(L, 1, "FLTK.Fl_Lua_Choice"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub::hash(key, 5);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "FLTK.Fl_Menu_")) break;
      *retval__ = static_cast<Fl_Menu_ *>(self);
      return 1;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "FLTK.Fl_Widget")) break;
      *retval__ = static_cast<Fl_Widget *>(self);
      return 1;
    }
  }
  return 0;
}

/** int Fl_Lua_Choice::handle(int)
 * inc/Fl_Lua_Choice.h:80
 */
static int Fl_Lua_Choice_handle(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int event = dub::checkinteger(L, 2);
    lua_pushnumber(L, self->handle(event));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "handle: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "handle: Unknown exception");
  }
  return dub::error(L);
}

/** Fl_Lua_Choice::Fl_Lua_Choice(int X, int Y, int W, int H, const char *L=0)
 * inc/Fl_Lua_Choice.h:82
 */
static int Fl_Lua_Choice_Fl_Lua_Choice(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 5) {
      int X = dub::checkinteger(L, 1);
      int Y = dub::checkinteger(L, 2);
      int W = dub::checkinteger(L, 3);
      int H = dub::checkinteger(L, 4);
      const char *Lstr = dub::checkstring(L, 5);
      Fl_Lua_Choice *retval__ = new Fl_Lua_Choice(X, Y, W, H, Lstr);
	retval__->ci.L=L;
	retval__->ci.cb=0;
      dub::pushudata(L, retval__, "FLTK.Fl_Lua_Choice", true);
      return 1;
    } else {
      int X = dub::checkinteger(L, 1);
      int Y = dub::checkinteger(L, 2);
      int W = dub::checkinteger(L, 3);
      int H = dub::checkinteger(L, 4);
      Fl_Lua_Choice *retval__ = new Fl_Lua_Choice(X, Y, W, H);
	retval__->ci.L=L;
	retval__->ci.cb=0;
      dub::pushudata(L, retval__, "FLTK.Fl_Lua_Choice", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Lua_Choice::value() const
 * inc/Fl_Lua_Choice.h:88
 */
static int Fl_Lua_Choice_value(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int type__ = lua_type(L, 2);
      if (type__ == LUA_TNUMBER) {
        int v = dub::checkinteger(L, 2);
        lua_pushnumber(L, self->value(v));
        return 1;
      } else {
        Fl_Menu_Item *v = *((Fl_Menu_Item **)dub::checksdata(L, 2, "FLTK.Fl_Menu_Item"));
        lua_pushnumber(L, self->value(v));
        return 1;
      }
    } else {
      lua_pushnumber(L, self->value());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "value: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "value: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::item_pathname(char *name, int namelen, const Fl_Menu_Item *finditem=0) const
 * inc/Fl_Menu_.h:56
 */
static int Fl_Lua_Choice_item_pathname(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 4) {
      char *name =(char*)dub::checkstring(L, 2);
      int namelen = dub::checkinteger(L, 3);
      Fl_Menu_Item *finditem = *((Fl_Menu_Item **)dub::checksdata(L, 4, "FLTK.Fl_Menu_Item"));
      lua_pushnumber(L, self->item_pathname(name, namelen, finditem));
      return 1;
    } else {
      char *name =(char*)dub::checkstring(L, 2);
      int namelen = dub::checkinteger(L, 3);
      lua_pushnumber(L, self->item_pathname(name, namelen));
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "item_pathname: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "item_pathname: Unknown exception");
  }
  return dub::error(L);
}

/** const Fl_Menu_Item* Fl_Menu_::picked(const Fl_Menu_Item *)
 * inc/Fl_Menu_.h:57
 */
static int Fl_Lua_Choice_picked(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    Fl_Menu_Item *p1 = *((Fl_Menu_Item **)dub::checksdata(L, 2, "FLTK.Fl_Menu_Item"));
    const Fl_Menu_Item *retval__ = self->picked(p1);
    if (!retval__) return 0;
    dub::pushudata(L, const_cast<Fl_Menu_Item*>(retval__), "FLTK.Fl_Menu_Item", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "picked: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "picked: Unknown exception");
  }
  return dub::error(L);
}

/** const Fl_Menu_Item* Fl_Menu_::find_item(const char *name)
 * inc/Fl_Menu_.h:58
 */
static int Fl_Lua_Choice_find_item(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int type__ = lua_type(L, 2);
    if (type__ == LUA_TSTRING) {
      const char *name = dub::checkstring(L, 2);
      const Fl_Menu_Item *retval__ = self->find_item(name);
      if (!retval__) return 0;
      dub::pushudata(L, const_cast<Fl_Menu_Item*>(retval__), "FLTK.Fl_Menu_Item", false);
      return 1;
    } else {
      Fl_Callback *p1 = *((Fl_Callback **)dub::checksdata(L, 2, "Fl_Callback"));
      const Fl_Menu_Item *retval__ = self->find_item(p1);
      if (!retval__) return 0;
      dub::pushudata(L, const_cast<Fl_Menu_Item*>(retval__), "FLTK.Fl_Menu_Item", false);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "find_item: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "find_item: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::find_index(const char *name) const
 * inc/Fl_Menu_.h:60
 */
static int Fl_Lua_Choice_find_index(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int type__ = lua_type(L, 2);
    void **ptr2__;
    if (type__ == LUA_TSTRING) {
      const char *name = dub::checkstring(L, 2);
      lua_pushnumber(L, self->find_index(name));
      return 1;
    } else if ( (ptr2__ = dub::issdata(L, 2, "FLTK.Fl_Menu_Item", type__)) ) {
      Fl_Menu_Item *item = *((Fl_Menu_Item **)ptr2__);
      lua_pushnumber(L, self->find_index(item));
      return 1;
    } else {
      Fl_Callback *cb = *((Fl_Callback **)dub::checksdata(L, 2, "Fl_Callback"));
      lua_pushnumber(L, self->find_index(cb));
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "find_index: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "find_index: Unknown exception");
  }
  return dub::error(L);
}

/** const Fl_Menu_Item* Fl_Menu_::test_shortcut()
 * inc/Fl_Menu_.h:75
 */
static int Fl_Lua_Choice_test_shortcut(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    const Fl_Menu_Item *retval__ = self->test_shortcut();
    if (!retval__) return 0;
    dub::pushudata(L, const_cast<Fl_Menu_Item*>(retval__), "FLTK.Fl_Menu_Item", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "test_shortcut: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "test_shortcut: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Menu_::global()
 * inc/Fl_Menu_.h:76
 */
static int Fl_Lua_Choice_global(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->global();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "global: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "global: Unknown exception");
  }
  return dub::error(L);
}

/** const Fl_Menu_Item* Fl_Menu_::menu() const
 * inc/Fl_Menu_.h:96
 */
static int Fl_Lua_Choice_menu(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      Fl_Menu_Item *m = *((Fl_Menu_Item **)dub::checksdata(L, 2, "FLTK.Fl_Menu_Item"));
      self->menu(m);
      return 0;
    } else {
      const Fl_Menu_Item *retval__ = self->menu();
      if (!retval__) return 0;
      dub::pushudata(L, const_cast<Fl_Menu_Item*>(retval__), "FLTK.Fl_Menu_Item", false);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "menu: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "menu: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Menu_::copy(const Fl_Menu_Item *m, void *user_data=0)
 * inc/Fl_Menu_.h:98
 */
static int Fl_Lua_Choice_copy(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      Fl_Menu_Item *m = *((Fl_Menu_Item **)dub::checksdata(L, 2, "FLTK.Fl_Menu_Item"));
      void *user_data = *((void **)dub::checksdata(L, 3, "void"));
      self->copy(m, user_data);
      return 0;
    } else {
      Fl_Menu_Item *m = *((Fl_Menu_Item **)dub::checksdata(L, 2, "FLTK.Fl_Menu_Item"));
      self->copy(m);
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "copy: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "copy: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::insert(int index, const char *, int shortcut, Fl_Callback *, void *=0, int=0)
 * inc/Fl_Menu_.h:99
 */
static int Fl_Lua_Choice_insert(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 7) {
      int type__ = lua_type(L, 4);
      if (type__ == LUA_TSTRING) {
        int index = dub::checkinteger(L, 2);
        const char *a = dub::checkstring(L, 3);
        const char *b = dub::checkstring(L, 4);
        Fl_Callback *c = *((Fl_Callback **)dub::checksdata(L, 5, "Fl_Callback"));
        void *d = *((void **)dub::checksdata(L, 6, "void"));
        int e = dub::checkinteger(L, 7);
        lua_pushnumber(L, self->insert(index, a, b, c, d, e));
        return 1;
      } else {
        int index = dub::checkinteger(L, 2);
        const char *p2 = dub::checkstring(L, 3);
        int shortcut = dub::checkinteger(L, 4);
        Fl_Callback *p4 = *((Fl_Callback **)dub::checksdata(L, 5, "Fl_Callback"));
        void *p5 = *((void **)dub::checksdata(L, 6, "void"));
        int p6 = dub::checkinteger(L, 7);
        lua_pushnumber(L, self->insert(index, p2, shortcut, p4, p5, p6));
        return 1;
      }
    } else if (top__ >= 6) {
      int type__ = lua_type(L, 4);
      if (type__ == LUA_TSTRING) {
        int index = dub::checkinteger(L, 2);
        const char *a = dub::checkstring(L, 3);
        const char *b = dub::checkstring(L, 4);
        Fl_Callback *c = *((Fl_Callback **)dub::checksdata(L, 5, "Fl_Callback"));
        void *d = *((void **)dub::checksdata(L, 6, "void"));
        lua_pushnumber(L, self->insert(index, a, b, c, d));
        return 1;
      } else {
        int index = dub::checkinteger(L, 2);
        const char *p2 = dub::checkstring(L, 3);
        int shortcut = dub::checkinteger(L, 4);
        Fl_Callback *p4 = *((Fl_Callback **)dub::checksdata(L, 5, "Fl_Callback"));
        void *p5 = *((void **)dub::checksdata(L, 6, "void"));
        lua_pushnumber(L, self->insert(index, p2, shortcut, p4, p5));
        return 1;
      }
    } else {
      int type__ = lua_type(L, 4);
      if (type__ == LUA_TSTRING) {
        int index = dub::checkinteger(L, 2);
        const char *a = dub::checkstring(L, 3);
        const char *b = dub::checkstring(L, 4);
        Fl_Callback *c = *((Fl_Callback **)dub::checksdata(L, 5, "Fl_Callback"));
        lua_pushnumber(L, self->insert(index, a, b, c));
        return 1;
      } else {
        int index = dub::checkinteger(L, 2);
        const char *p2 = dub::checkstring(L, 3);
        int shortcut = dub::checkinteger(L, 4);
        Fl_Callback *p4 = *((Fl_Callback **)dub::checksdata(L, 5, "Fl_Callback"));
        lua_pushnumber(L, self->insert(index, p2, shortcut, p4));
        return 1;
      }
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "insert: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "insert: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::add(const char *, int shortcut, Fl_Callback *, void *=0, int=0)
 * inc/Fl_Menu_.h:100
 */
static int Fl_Lua_Choice_add(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 6) {
      int type__ = lua_type(L, 3);
      if (type__ == LUA_TSTRING) {
        const char *a = dub::checkstring(L, 2);
        const char *b = dub::checkstring(L, 3);
        Fl_Callback *c = *((Fl_Callback **)dub::checksdata(L, 4, "Fl_Callback"));
        void *d = *((void **)dub::checksdata(L, 5, "void"));
        int e = dub::checkinteger(L, 6);
        lua_pushnumber(L, self->add(a, b, c, d, e));
        return 1;
      } else {
        const char *p1 = dub::checkstring(L, 2);
        int shortcut = dub::checkinteger(L, 3);
        Fl_Callback *p3 = *((Fl_Callback **)dub::checksdata(L, 4, "Fl_Callback"));
        void *p4 = *((void **)dub::checksdata(L, 5, "void"));
        int p5 = dub::checkinteger(L, 6);
        lua_pushnumber(L, self->add(p1, shortcut, p3, p4, p5));
        return 1;
      }
    } else if (top__ >= 5) {
      int type__ = lua_type(L, 3);
      if (type__ == LUA_TSTRING) {
        const char *a = dub::checkstring(L, 2);
        const char *b = dub::checkstring(L, 3);
        Fl_Callback *c = *((Fl_Callback **)dub::checksdata(L, 4, "Fl_Callback"));
        void *d = *((void **)dub::checksdata(L, 5, "void"));
        lua_pushnumber(L, self->add(a, b, c, d));
        return 1;
      } else {
        const char *p1 = dub::checkstring(L, 2);
        int shortcut = dub::checkinteger(L, 3);
        Fl_Callback *p3 = *((Fl_Callback **)dub::checksdata(L, 4, "Fl_Callback"));
        void *p4 = *((void **)dub::checksdata(L, 5, "void"));
        lua_pushnumber(L, self->add(p1, shortcut, p3, p4));
        return 1;
      }
    } else if (top__ >= 4) {
      int type__ = lua_type(L, 3);
      if (type__ == LUA_TSTRING) {
        const char *a = dub::checkstring(L, 2);
        const char *b = dub::checkstring(L, 3);
        Fl_Callback *c = *((Fl_Callback **)dub::checksdata(L, 4, "Fl_Callback"));
        lua_pushnumber(L, self->add(a, b, c));
        return 1;
      } else {
        const char *p1 = dub::checkstring(L, 2);
        int shortcut = dub::checkinteger(L, 3);
        Fl_Callback *p3 = *((Fl_Callback **)dub::checksdata(L, 4, "Fl_Callback"));
        lua_pushnumber(L, self->add(p1, shortcut, p3));
        return 1;
      }
    } else {
      const char *p1 = dub::checkstring(L, 2);
      lua_pushnumber(L, self->add(p1));
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "add: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "add: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::size() const
 * inc/Fl_Menu_.h:110
 */
static int Fl_Lua_Choice_size(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      int W = dub::checkinteger(L, 2);
      int H = dub::checkinteger(L, 3);
      self->size(W, H);
      return 0;
    } else {
      lua_pushnumber(L, self->size());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "size: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "size: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Menu_::clear()
 * inc/Fl_Menu_.h:112
 */
static int Fl_Lua_Choice_clear(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->clear();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "clear: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "clear: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::clear_submenu(int index)
 * inc/Fl_Menu_.h:113
 */
static int Fl_Lua_Choice_clear_submenu(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int index = dub::checkinteger(L, 2);
    lua_pushnumber(L, self->clear_submenu(index));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "clear_submenu: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "clear_submenu: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Menu_::replace(int, const char *)
 * inc/Fl_Menu_.h:114
 */
static int Fl_Lua_Choice_replace(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int p1 = dub::checkinteger(L, 2);
    const char *p2 = dub::checkstring(L, 3);
    self->replace(p1, p2);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "replace: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "replace: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Menu_::remove(int)
 * inc/Fl_Menu_.h:115
 */
static int Fl_Lua_Choice_remove(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int p1 = dub::checkinteger(L, 2);
    self->remove(p1);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "remove: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "remove: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Menu_::shortcut(int i, int s)
 * inc/Fl_Menu_.h:117
 */
static int Fl_Lua_Choice_shortcut(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int i = dub::checkinteger(L, 2);
    int s = dub::checkinteger(L, 3);
    self->shortcut(i, s);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "shortcut: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "shortcut: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Menu_::mode(int i, int fl)
 * inc/Fl_Menu_.h:119
 */
static int Fl_Lua_Choice_mode(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      int i = dub::checkinteger(L, 2);
      int fl = dub::checkinteger(L, 3);
      self->mode(i, fl);
      return 0;
    } else {
      int i = dub::checkinteger(L, 2);
      lua_pushnumber(L, self->mode(i));
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "mode: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "mode: Unknown exception");
  }
  return dub::error(L);
}

/** const Fl_Menu_Item* Fl_Menu_::mvalue() const
 * inc/Fl_Menu_.h:124
 */
static int Fl_Lua_Choice_mvalue(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    const Fl_Menu_Item *retval__ = self->mvalue();
    if (!retval__) return 0;
    dub::pushudata(L, const_cast<Fl_Menu_Item*>(retval__), "FLTK.Fl_Menu_Item", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "mvalue: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "mvalue: Unknown exception");
  }
  return dub::error(L);
}

/** const char* Fl_Menu_::text() const
 * inc/Fl_Menu_.h:136
 */
static int Fl_Lua_Choice_text(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int i = dub::checkinteger(L, 2);
      lua_pushstring(L, self->text(i));
      return 1;
    } else {
      lua_pushstring(L, self->text());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "text: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "text: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::textfont() const
 * inc/Fl_Menu_.h:141
 */
static int Fl_Lua_Choice_textfont(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int c = dub::checkinteger(L, 2);
      self->textfont(c);
      return 0;
    } else {
      lua_pushnumber(L, self->textfont());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "textfont: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "textfont: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::textsize() const
 * inc/Fl_Menu_.h:145
 */
static int Fl_Lua_Choice_textsize(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int c = dub::checkinteger(L, 2);
      self->textsize(c);
      return 0;
    } else {
      lua_pushnumber(L, self->textsize());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "textsize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "textsize: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::textcolor() const
 * inc/Fl_Menu_.h:149
 */
static int Fl_Lua_Choice_textcolor(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int c = dub::checkinteger(L, 2);
      self->textcolor(c);
      return 0;
    } else {
      lua_pushnumber(L, self->textcolor());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "textcolor: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "textcolor: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::down_box() const
 * inc/Fl_Menu_.h:159
 */
static int Fl_Lua_Choice_down_box(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int b = dub::checkinteger(L, 2);
      self->down_box((Fl_Boxtype)b);
      return 0;
    } else {
      lua_pushnumber(L, self->down_box());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "down_box: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "down_box: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Menu_::down_color() const
 * inc/Fl_Menu_.h:164
 */
static int Fl_Lua_Choice_down_color(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      unsigned c = dub::checkinteger(L, 2);
      self->down_color(c);
      return 0;
    } else {
      lua_pushnumber(L, self->down_color());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "down_color: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "down_color: Unknown exception");
  }
  return dub::error(L);
}

/** Fl_Group* Fl_Widget::parent() const
 * inc/Fl_Widget.h:243
 */
static int Fl_Lua_Choice_parent(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      Fl_Group *p = *((Fl_Group **)dub::checksdata(L, 2, "FLTK.Fl_Group"));
      self->parent(p);
      return 0;
    } else {
      Fl_Group *retval__ = self->parent();
      if (!retval__) return 0;
      dub::pushudata(L, retval__, "FLTK.Fl_Group", false);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "parent: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "parent: Unknown exception");
  }
  return dub::error(L);
}

/** unsigned char Fl_Widget::type() const
 * inc/Fl_Widget.h:263
 */
static int Fl_Lua_Choice_type(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      unsigned char t = dub::checkinteger(L, 2);
      self->type(t);
      return 0;
    } else {
      lua_pushnumber(L, self->type());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "type: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "type: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::x() const
 * inc/Fl_Widget.h:273
 */
static int Fl_Lua_Choice_x(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->x());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "x: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "x: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::y() const
 * inc/Fl_Widget.h:278
 */
static int Fl_Lua_Choice_y(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->y());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "y: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "y: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::w() const
 * inc/Fl_Widget.h:283
 */
static int Fl_Lua_Choice_w(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->w());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "w: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "w: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::h() const
 * inc/Fl_Widget.h:288
 */
static int Fl_Lua_Choice_h(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->h());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "h: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "h: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void Fl_Widget::resize(int x, int y, int w, int h)
 * inc/Fl_Widget.h:309
 */
static int Fl_Lua_Choice_resize(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int x = dub::checkinteger(L, 2);
    int y = dub::checkinteger(L, 3);
    int w = dub::checkinteger(L, 4);
    int h = dub::checkinteger(L, 5);
    self->resize(x, y, w, h);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "resize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "resize: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::damage_resize(int, int, int, int)
 * inc/Fl_Widget.h:312
 */
static int Fl_Lua_Choice_damage_resize(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int p1 = dub::checkinteger(L, 2);
    int p2 = dub::checkinteger(L, 3);
    int p3 = dub::checkinteger(L, 4);
    int p4 = dub::checkinteger(L, 5);
    lua_pushnumber(L, self->damage_resize(p1, p2, p3, p4));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "damage_resize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "damage_resize: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::position(int X, int Y)
 * inc/Fl_Widget.h:321
 */
static int Fl_Lua_Choice_position(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int X = dub::checkinteger(L, 2);
    int Y = dub::checkinteger(L, 3);
    self->position(X, Y);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "position: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "position: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::align() const
 * inc/Fl_Widget.h:337
 */
static int Fl_Lua_Choice_align(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int alignment = dub::checkinteger(L, 2);
      self->align(alignment);
      return 0;
    } else {
      lua_pushnumber(L, self->align());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "align: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "align: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::box() const
 * inc/Fl_Widget.h:352
 */
static int Fl_Lua_Choice_box(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int new_box = dub::checkinteger(L, 2);
      self->box((Fl_Boxtype)new_box);
      return 0;
    } else {
      lua_pushnumber(L, self->box());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "box: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "box: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::color() const
 * inc/Fl_Widget.h:367
 */
static int Fl_Lua_Choice_color(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      int bg = dub::checkinteger(L, 2);
      int sel = dub::checkinteger(L, 3);
      self->color(bg, sel);
      return 0;
    } else if (top__ >= 2) {
      int bg = dub::checkinteger(L, 2);
      self->color(bg);
      return 0;
    } else {
      lua_pushnumber(L, self->color());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "color: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "color: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::selection_color() const
 * inc/Fl_Widget.h:385
 */
static int Fl_Lua_Choice_selection_color(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int a = dub::checkinteger(L, 2);
      self->selection_color(a);
      return 0;
    } else {
      lua_pushnumber(L, self->selection_color());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "selection_color: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "selection_color: Unknown exception");
  }
  return dub::error(L);
}

/** const char* Fl_Widget::label() const
 * inc/Fl_Widget.h:410
 */
static int Fl_Lua_Choice_label(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      Fl_Labeltype a = (Fl_Labeltype)dub::checkinteger(L, 2);
      const char *b = dub::checkstring(L, 3);
      self->label(a, b);
      return 0;
    } else if (top__ >= 2) {
      const char *text = dub::checkstring(L, 2);
      self->label(text);
      return 0;
    } else {
      lua_pushstring(L, self->label());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "label: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "label: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::copy_label(const char *new_label)
 * inc/Fl_Widget.h:434
 */
static int Fl_Lua_Choice_copy_label(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    const char *new_label = dub::checkstring(L, 2);
    self->copy_label(new_label);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "copy_label: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "copy_label: Unknown exception");
  }
  return dub::error(L);
}

/** Fl_Labeltype Fl_Widget::labeltype() const
 * inc/Fl_Widget.h:445
 */
static int Fl_Lua_Choice_labeltype(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      Fl_Labeltype a = (Fl_Labeltype)dub::checkinteger(L, 2);
      self->labeltype(a);
      return 0;
    } else {
      lua_pushnumber(L, self->labeltype());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "labeltype: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "labeltype: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::labelcolor() const
 * inc/Fl_Widget.h:461
 */
static int Fl_Lua_Choice_labelcolor(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int c = dub::checkinteger(L, 2);
      self->labelcolor(c);
      return 0;
    } else {
      lua_pushnumber(L, self->labelcolor());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "labelcolor: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "labelcolor: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::labelfont() const
 * inc/Fl_Widget.h:476
 */
static int Fl_Lua_Choice_labelfont(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int f = dub::checkinteger(L, 2);
      self->labelfont(f);
      return 0;
    } else {
      lua_pushnumber(L, self->labelfont());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "labelfont: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "labelfont: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::labelsize() const
 * inc/Fl_Widget.h:491
 */
static int Fl_Lua_Choice_labelsize(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int pix = dub::checkinteger(L, 2);
      self->labelsize(pix);
      return 0;
    } else {
      lua_pushnumber(L, self->labelsize());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "labelsize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "labelsize: Unknown exception");
  }
  return dub::error(L);
}

/** Fl_Image* Fl_Widget::image()
 * inc/Fl_Widget.h:503
 */
static int Fl_Lua_Choice_image(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      Fl_Image *img = *((Fl_Image **)dub::checksdata(L, 2, "FLTK.Fl_Image"));
      self->image(img);
      return 0;
    } else {
      Fl_Image *retval__ = self->image();
      if (!retval__) return 0;
      dub::pushudata(L, retval__, "FLTK.Fl_Image", false);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "image: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "image: Unknown exception");
  }
  return dub::error(L);
}

/** Fl_Image* Fl_Widget::deimage()
 * inc/Fl_Widget.h:522
 */
static int Fl_Lua_Choice_deimage(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      Fl_Image *img = *((Fl_Image **)dub::checksdata(L, 2, "FLTK.Fl_Image"));
      self->deimage(img);
      return 0;
    } else {
      Fl_Image *retval__ = self->deimage();
      if (!retval__) return 0;
      dub::pushudata(L, retval__, "FLTK.Fl_Image", false);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "deimage: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "deimage: Unknown exception");
  }
  return dub::error(L);
}

/** const char* Fl_Widget::tooltip() const
 * inc/Fl_Widget.h:541
 */
static int Fl_Lua_Choice_tooltip(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      const char *text = dub::checkstring(L, 2);
      self->tooltip(text);
      return 0;
    } else {
      lua_pushstring(L, self->tooltip());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "tooltip: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "tooltip: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::copy_tooltip(const char *text)
 * inc/Fl_Widget.h:544
 */
static int Fl_Lua_Choice_copy_tooltip(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    const char *text = dub::checkstring(L, 2);
    self->copy_tooltip(text);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "copy_tooltip: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "copy_tooltip: Unknown exception");
  }
  return dub::error(L);
}

/** Fl_Callback_p Fl_Widget::callback() const
 * inc/Fl_Widget.h:550
 */
static int Fl_Lua_Choice_callback(lua_State *L) {
	try {
		Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
		int top__ = lua_gettop(L);
		if (top__ >= 3) {
			self->ci.cb=strdup(luaL_checkstring(L,2));
			self->ci.udat=luaL_checkinteger(L,3);
			self->callback(luaWidgetCallbackHelper,&self->ci);
			return 0;
		} else if (top__ >= 2) {
			self->ci.cb=strdup(luaL_checkstring(L,2));
			self->ci.udat=0;
			self->callback(luaWidgetCallbackHelper,&self->ci);
			return 0;
		} else {
			lua_pushstring(L,self->ci.cb);
			return 1;
		}
	} catch (std::exception &e) {
		lua_pushfstring(L, "callback: %s", e.what());
	} catch (...) {
		lua_pushfstring(L, "callback: Unknown exception");
	}
	return dub::error(L);
}

/** void* Fl_Widget::user_data() const
 * inc/Fl_Widget.h:582
 */
static int Fl_Lua_Choice_user_data(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      void *v = *((void **)dub::checksdata(L, 2, "void"));
      self->user_data(v);
      return 0;
    } else {
      self->user_data();
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "user_data: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "user_data: Unknown exception");
  }
  return dub::error(L);
}

/** long Fl_Widget::argument() const
 * inc/Fl_Widget.h:592
 */
static int Fl_Lua_Choice_argument(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      long *v = *((long **)dub::checksdata(L, 2, "long"));
      self->argument(*v);
      return 0;
    } else {
      dub::pushudata(L, new long(self->argument()), "long", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "argument: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "argument: Unknown exception");
  }
  return dub::error(L);
}

/** Fl_When Fl_Widget::when() const
 * inc/Fl_Widget.h:608
 */
static int Fl_Lua_Choice_when(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      unsigned char i = dub::checkinteger(L, 2);
      self->when(i);
      return 0;
    } else {
      dub::pushudata(L, new Fl_When(self->when()), "Fl_When", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "when: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "when: Unknown exception");
  }
  return dub::error(L);
}

/** unsigned int Fl_Widget::visible() const
 * inc/Fl_Widget.h:647
 */
static int Fl_Lua_Choice_visible(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->visible());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "visible: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "visible: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::visible_r() const
 * inc/Fl_Widget.h:653
 */
static int Fl_Lua_Choice_visible_r(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->visible_r());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "visible_r: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "visible_r: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void Fl_Widget::show()
 * inc/Fl_Widget.h:672
 */
static int Fl_Lua_Choice_show(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->show();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "show: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "show: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void Fl_Widget::hide()
 * inc/Fl_Widget.h:677
 */
static int Fl_Lua_Choice_hide(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->hide();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "hide: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "hide: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::set_visible()
 * inc/Fl_Widget.h:683
 */
static int Fl_Lua_Choice_set_visible(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->set_visible();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "set_visible: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "set_visible: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::clear_visible()
 * inc/Fl_Widget.h:689
 */
static int Fl_Lua_Choice_clear_visible(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->clear_visible();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "clear_visible: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "clear_visible: Unknown exception");
  }
  return dub::error(L);
}

/** unsigned int Fl_Widget::active() const
 * inc/Fl_Widget.h:695
 */
static int Fl_Lua_Choice_active(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->active());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "active: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "active: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::active_r() const
 * inc/Fl_Widget.h:701
 */
static int Fl_Lua_Choice_active_r(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->active_r());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "active_r: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "active_r: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::activate()
 * inc/Fl_Widget.h:708
 */
static int Fl_Lua_Choice_activate(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->activate();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "activate: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "activate: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::deactivate()
 * inc/Fl_Widget.h:724
 */
static int Fl_Lua_Choice_deactivate(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->deactivate();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "deactivate: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "deactivate: Unknown exception");
  }
  return dub::error(L);
}

/** unsigned int Fl_Widget::output() const
 * inc/Fl_Widget.h:734
 */
static int Fl_Lua_Choice_output(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->output());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "output: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "output: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::set_output()
 * inc/Fl_Widget.h:739
 */
static int Fl_Lua_Choice_set_output(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->set_output();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "set_output: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "set_output: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::clear_output()
 * inc/Fl_Widget.h:744
 */
static int Fl_Lua_Choice_clear_output(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->clear_output();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "clear_output: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "clear_output: Unknown exception");
  }
  return dub::error(L);
}

/** unsigned int Fl_Widget::takesevents() const
 * inc/Fl_Widget.h:751
 */
static int Fl_Lua_Choice_takesevents(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->takesevents());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "takesevents: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "takesevents: Unknown exception");
  }
  return dub::error(L);
}

/** unsigned int Fl_Widget::changed() const
 * inc/Fl_Widget.h:768
 */
static int Fl_Lua_Choice_changed(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->changed());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "changed: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "changed: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::set_changed()
 * inc/Fl_Widget.h:773
 */
static int Fl_Lua_Choice_set_changed(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->set_changed();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "set_changed: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "set_changed: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::clear_changed()
 * inc/Fl_Widget.h:778
 */
static int Fl_Lua_Choice_clear_changed(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->clear_changed();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "clear_changed: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "clear_changed: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::clear_active()
 * inc/Fl_Widget.h:784
 */
#if (FL_MAJOR_VERSION>=1 && FL_MINOR_VERSION>=3 && FL_PATCH_VERSION>=3)
static int Fl_Lua_Choice_clear_active(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->clear_active();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "clear_active: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "clear_active: Unknown exception");
  }
  return dub::error(L);
}
#endif

/** void Fl_Widget::set_active()
 * inc/Fl_Widget.h:790
 */
#if (FL_MAJOR_VERSION>=1 && FL_MINOR_VERSION>=3 && FL_PATCH_VERSION>=3)
static int Fl_Lua_Choice_set_active(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->set_active();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "set_active: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "set_active: Unknown exception");
  }
  return dub::error(L);
}
#endif

/** int Fl_Widget::take_focus()
 * inc/Fl_Widget.h:799
 */
static int Fl_Lua_Choice_take_focus(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->take_focus());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "take_focus: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "take_focus: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::set_visible_focus()
 * inc/Fl_Widget.h:807
 */
static int Fl_Lua_Choice_set_visible_focus(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->set_visible_focus();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "set_visible_focus: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "set_visible_focus: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::clear_visible_focus()
 * inc/Fl_Widget.h:813
 */
static int Fl_Lua_Choice_clear_visible_focus(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->clear_visible_focus();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "clear_visible_focus: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "clear_visible_focus: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::visible_focus(int v)
 * inc/Fl_Widget.h:819
 */
static int Fl_Lua_Choice_visible_focus(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int v = dub::checkinteger(L, 2);
      self->visible_focus(v);
      return 0;
    } else {
      lua_pushnumber(L, self->visible_focus());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "visible_focus: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "visible_focus: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::do_callback()
 * inc/Fl_Widget.h:840
 */
static int Fl_Lua_Choice_do_callback(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      int type__ = lua_type(L, 3);
      void **ptr3__;
      if ( (ptr3__ = dub::issdata(L, 3, "long", type__)) ) {
        Fl_Widget *o = *((Fl_Widget **)dub::checksdata(L, 2, "FLTK.Fl_Widget"));
        long *arg = *((long **)ptr3__);
        self->do_callback(o, *arg);
        return 0;
      } else {
        Fl_Widget *o = *((Fl_Widget **)dub::checksdata(L, 2, "FLTK.Fl_Widget"));
        void *arg = *((void **)dub::checksdata(L, 3, "void"));
        self->do_callback(o, arg);
        return 0;
      }
    } else if (top__ >= 2) {
      Fl_Widget *o = *((Fl_Widget **)dub::checksdata(L, 2, "FLTK.Fl_Widget"));
      self->do_callback(o);
      return 0;
    } else {
      self->do_callback();
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "do_callback: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "do_callback: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::_set_fullscreen()
 * inc/Fl_Widget.h:861
 */
static int Fl_Lua_Choice__set_fullscreen(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->_set_fullscreen();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "_set_fullscreen: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "_set_fullscreen: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::_clear_fullscreen()
 * inc/Fl_Widget.h:862
 */
static int Fl_Lua_Choice__clear_fullscreen(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->_clear_fullscreen();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "_clear_fullscreen: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "_clear_fullscreen: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::contains(const Fl_Widget *w) const
 * inc/Fl_Widget.h:869
 */
static int Fl_Lua_Choice_contains(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    Fl_Widget *w = *((Fl_Widget **)dub::checksdata(L, 2, "FLTK.Fl_Widget"));
    lua_pushnumber(L, self->contains(w));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "contains: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "contains: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::inside(const Fl_Widget *wgt) const
 * inc/Fl_Widget.h:877
 */
static int Fl_Lua_Choice_inside(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    Fl_Widget *wgt = *((Fl_Widget **)dub::checksdata(L, 2, "FLTK.Fl_Widget"));
    lua_pushnumber(L, self->inside(wgt));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "inside: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "inside: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::redraw()
 * inc/Fl_Widget.h:882
 */
static int Fl_Lua_Choice_redraw(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->redraw();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "redraw: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "redraw: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::redraw_label()
 * inc/Fl_Widget.h:888
 */
static int Fl_Lua_Choice_redraw_label(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    self->redraw_label();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "redraw_label: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "redraw_label: Unknown exception");
  }
  return dub::error(L);
}

/** unsigned char Fl_Widget::damage() const
 * inc/Fl_Widget.h:896
 */
static int Fl_Lua_Choice_damage(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 6) {
      unsigned char c = dub::checkinteger(L, 2);
      int x = dub::checkinteger(L, 3);
      int y = dub::checkinteger(L, 4);
      int w = dub::checkinteger(L, 5);
      int h = dub::checkinteger(L, 6);
      self->damage(c, x, y, w, h);
      return 0;
    } else if (top__ >= 2) {
      unsigned char c = dub::checkinteger(L, 2);
      self->damage(c);
      return 0;
    } else {
      lua_pushnumber(L, self->damage());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "damage: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "damage: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::clear_damage(unsigned char c=0)
 * inc/Fl_Widget.h:910
 */
static int Fl_Lua_Choice_clear_damage(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      unsigned char c = dub::checkinteger(L, 2);
      self->clear_damage(c);
      return 0;
    } else {
      self->clear_damage();
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "clear_damage: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "clear_damage: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::draw_label(int, int, int, int, int) const
 * inc/Fl_Widget.h:927
 */
static int Fl_Lua_Choice_draw_label(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int p1 = dub::checkinteger(L, 2);
    int p2 = dub::checkinteger(L, 3);
    int p3 = dub::checkinteger(L, 4);
    int p4 = dub::checkinteger(L, 5);
    int p5 = dub::checkinteger(L, 6);
    self->draw_label(p1, p2, p3, p4, p5);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "draw_label: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "draw_label: Unknown exception");
  }
  return dub::error(L);
}

/** void Fl_Widget::measure_label(int &ww, int &hh) const
 * inc/Fl_Widget.h:936
 */
static int Fl_Lua_Choice_measure_label(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int ww = dub::checkinteger(L, 2);
    int hh = dub::checkinteger(L, 3);
    self->measure_label(ww, hh);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "measure_label: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "measure_label: Unknown exception");
  }
  return dub::error(L);
}

/** Fl_Window* Fl_Widget::window() const
 * inc/Fl_Widget.h:938
 */
static int Fl_Lua_Choice_window(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    Fl_Window *retval__ = self->window();
    if (!retval__) return 0;
    dub::pushudata(L, retval__, "FLTK.Fl_Window", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "window: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "window: Unknown exception");
  }
  return dub::error(L);
}

/** Fl_Window* Fl_Widget::top_window() const
 * inc/Fl_Widget.h:939
 */
#if (FL_MAJOR_VERSION>=1 && FL_MINOR_VERSION>=3 && FL_PATCH_VERSION>=3)
static int Fl_Lua_Choice_top_window(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    Fl_Window *retval__ = self->top_window();
    if (!retval__) return 0;
    dub::pushudata(L, retval__, "FLTK.Fl_Window", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "top_window: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "top_window: Unknown exception");
  }
  return dub::error(L);
}
#endif

/** Fl_Window* Fl_Widget::top_window_offset(int &xoff, int &yoff) const
 * inc/Fl_Widget.h:940
 */
#if (FL_MAJOR_VERSION>=1 && FL_MINOR_VERSION>=3 && FL_PATCH_VERSION>=3)
static int Fl_Lua_Choice_top_window_offset(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int xoff = dub::checkinteger(L, 2);
    int yoff = dub::checkinteger(L, 3);
    Fl_Window *retval__ = self->top_window_offset(xoff, yoff);
    if (!retval__) return 0;
    dub::pushudata(L, retval__, "FLTK.Fl_Window", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "top_window_offset: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "top_window_offset: Unknown exception");
  }
  return dub::error(L);
}
#endif

/** virtual Fl_Group* Fl_Widget::as_group()
 * inc/Fl_Widget.h:965
 */
static int Fl_Lua_Choice_as_group(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    Fl_Group *retval__ = self->as_group();
    if (!retval__) return 0;
    dub::pushudata(L, retval__, "FLTK.Fl_Group", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "as_group: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "as_group: Unknown exception");
  }
  return dub::error(L);
}

/** virtual Fl_Window* Fl_Widget::as_window()
 * inc/Fl_Widget.h:979
 */
static int Fl_Lua_Choice_as_window(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    Fl_Window *retval__ = self->as_window();
    if (!retval__) return 0;
    dub::pushudata(L, retval__, "FLTK.Fl_Window", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "as_window: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "as_window: Unknown exception");
  }
  return dub::error(L);
}

/** virtual class Fl_Gl_Window* Fl_Widget::as_gl_window()
 * inc/Fl_Widget.h:991
 */
static int Fl_Lua_Choice_as_gl_window(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    class Fl_Gl_Window *retval__ = self->as_gl_window();
    if (!retval__) return 0;
    dub::pushudata(L, retval__, "class Fl_Gl_Window", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "as_gl_window: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "as_gl_window: Unknown exception");
  }
  return dub::error(L);
}

/** int Fl_Widget::use_accents_menu()
 * inc/Fl_Widget.h:995
 */
#if (FL_MAJOR_VERSION>=1 && FL_MINOR_VERSION>=3 && FL_PATCH_VERSION>=3)
static int Fl_Lua_Choice_use_accents_menu(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    lua_pushnumber(L, self->use_accents_menu());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "use_accents_menu: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "use_accents_menu: Unknown exception");
  }
  return dub::error(L);
}
#endif

/** int Fl_Widget::color2() const
 * inc/Fl_Widget.h:1000
 */
static int Fl_Lua_Choice_color2(lua_State *L) {
  try {
    Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata(L, 1, "FLTK.Fl_Lua_Choice"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      unsigned a = dub::checkinteger(L, 2);
      self->color2(a);
      return 0;
    } else {
      lua_pushnumber(L, self->color2());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "color2: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "color2: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int Fl_Lua_Choice___tostring(lua_State *L) {
  Fl_Lua_Choice *self = *((Fl_Lua_Choice **)dub::checksdata_n(L, 1, "FLTK.Fl_Lua_Choice"));
  lua_pushfstring(L, "FLTK.Fl_Lua_Choice: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg Fl_Lua_Choice_member_methods[] = {
  { "__gc"         , Fl_Lua_Choice__Fl_Lua_Choice },
  { "_cast_"       , Fl_Lua_Choice__cast_     },
  { "handle"       , Fl_Lua_Choice_handle     },
  { "new"          , Fl_Lua_Choice_Fl_Lua_Choice  },
  { "value"        , Fl_Lua_Choice_value      },
  { "item_pathname", Fl_Lua_Choice_item_pathname },
  { "picked"       , Fl_Lua_Choice_picked     },
  { "find_item"    , Fl_Lua_Choice_find_item  },
  { "find_index"   , Fl_Lua_Choice_find_index },
  { "test_shortcut", Fl_Lua_Choice_test_shortcut },
  { "global"       , Fl_Lua_Choice_global     },
  { "menu"         , Fl_Lua_Choice_menu       },
  { "copy"         , Fl_Lua_Choice_copy       },
  { "insert"       , Fl_Lua_Choice_insert     },
  { "add"          , Fl_Lua_Choice_add        },
  { "size"         , Fl_Lua_Choice_size       },
  { "clear"        , Fl_Lua_Choice_clear      },
  { "clear_submenu", Fl_Lua_Choice_clear_submenu },
  { "replace"      , Fl_Lua_Choice_replace    },
  { "remove"       , Fl_Lua_Choice_remove     },
  { "shortcut"     , Fl_Lua_Choice_shortcut   },
  { "mode"         , Fl_Lua_Choice_mode       },
  { "mvalue"       , Fl_Lua_Choice_mvalue     },
  { "text"         , Fl_Lua_Choice_text       },
  { "textfont"     , Fl_Lua_Choice_textfont   },
  { "textsize"     , Fl_Lua_Choice_textsize   },
  { "textcolor"    , Fl_Lua_Choice_textcolor  },
  { "down_box"     , Fl_Lua_Choice_down_box   },
  { "down_color"   , Fl_Lua_Choice_down_color },
  { "parent"       , Fl_Lua_Choice_parent     },
  { "Type"         , Fl_Lua_Choice_type       },
  { "x"            , Fl_Lua_Choice_x          },
  { "y"            , Fl_Lua_Choice_y          },
  { "w"            , Fl_Lua_Choice_w          },
  { "h"            , Fl_Lua_Choice_h          },
  { "resize"       , Fl_Lua_Choice_resize     },
  { "damage_resize", Fl_Lua_Choice_damage_resize },
  { "position"     , Fl_Lua_Choice_position   },
  { "align"        , Fl_Lua_Choice_align      },
  { "box"          , Fl_Lua_Choice_box        },
  { "color"        , Fl_Lua_Choice_color      },
  { "selection_color", Fl_Lua_Choice_selection_color },
  { "label"        , Fl_Lua_Choice_label      },
  { "copy_label"   , Fl_Lua_Choice_copy_label },
  { "labeltype"    , Fl_Lua_Choice_labeltype  },
  { "labelcolor"   , Fl_Lua_Choice_labelcolor },
  { "labelfont"    , Fl_Lua_Choice_labelfont  },
  { "labelsize"    , Fl_Lua_Choice_labelsize  },
  { "image"        , Fl_Lua_Choice_image      },
  { "deimage"      , Fl_Lua_Choice_deimage    },
  { "tooltip"      , Fl_Lua_Choice_tooltip    },
  { "copy_tooltip" , Fl_Lua_Choice_copy_tooltip },
  { "callback"     , Fl_Lua_Choice_callback   },
  { "user_data"    , Fl_Lua_Choice_user_data  },
  { "argument"     , Fl_Lua_Choice_argument   },
  { "when"         , Fl_Lua_Choice_when       },
  { "visible"      , Fl_Lua_Choice_visible    },
  { "visible_r"    , Fl_Lua_Choice_visible_r  },
  { "show"         , Fl_Lua_Choice_show       },
  { "hide"         , Fl_Lua_Choice_hide       },
  { "set_visible"  , Fl_Lua_Choice_set_visible },
  { "clear_visible", Fl_Lua_Choice_clear_visible },
  { "active"       , Fl_Lua_Choice_active     },
  { "active_r"     , Fl_Lua_Choice_active_r   },
  { "activate"     , Fl_Lua_Choice_activate   },
  { "deactivate"   , Fl_Lua_Choice_deactivate },
  { "output"       , Fl_Lua_Choice_output     },
  { "set_output"   , Fl_Lua_Choice_set_output },
  { "clear_output" , Fl_Lua_Choice_clear_output },
  { "takesevents"  , Fl_Lua_Choice_takesevents },
  { "changed"      , Fl_Lua_Choice_changed    },
  { "set_changed"  , Fl_Lua_Choice_set_changed },
  { "clear_changed", Fl_Lua_Choice_clear_changed },
#if (FL_MAJOR_VERSION>=1 && FL_MINOR_VERSION>=3 && FL_PATCH_VERSION>=3)
  { "clear_active" , Fl_Lua_Choice_clear_active },
#endif
#if (FL_MAJOR_VERSION>=1 && FL_MINOR_VERSION>=3 && FL_PATCH_VERSION>=3)
  { "set_active"   , Fl_Lua_Choice_set_active },
#endif
  { "take_focus"   , Fl_Lua_Choice_take_focus },
  { "set_visible_focus", Fl_Lua_Choice_set_visible_focus },
  { "clear_visible_focus", Fl_Lua_Choice_clear_visible_focus },
  { "visible_focus", Fl_Lua_Choice_visible_focus },
  { "do_callback"  , Fl_Lua_Choice_do_callback },
  { "_set_fullscreen", Fl_Lua_Choice__set_fullscreen },
  { "_clear_fullscreen", Fl_Lua_Choice__clear_fullscreen },
  { "contains"     , Fl_Lua_Choice_contains   },
  { "inside"       , Fl_Lua_Choice_inside     },
  { "redraw"       , Fl_Lua_Choice_redraw     },
  { "redraw_label" , Fl_Lua_Choice_redraw_label },
  { "damage"       , Fl_Lua_Choice_damage     },
  { "clear_damage" , Fl_Lua_Choice_clear_damage },
  { "draw_label"   , Fl_Lua_Choice_draw_label },
  { "measure_label", Fl_Lua_Choice_measure_label },
  { "window"       , Fl_Lua_Choice_window     },
#if (FL_MAJOR_VERSION>=1 && FL_MINOR_VERSION>=3 && FL_PATCH_VERSION>=3)
  { "top_window"   , Fl_Lua_Choice_top_window },
#endif
#if (FL_MAJOR_VERSION>=1 && FL_MINOR_VERSION>=3 && FL_PATCH_VERSION>=3)
  { "top_window_offset", Fl_Lua_Choice_top_window_offset },
#endif
  { "as_group"     , Fl_Lua_Choice_as_group   },
  { "as_window"    , Fl_Lua_Choice_as_window  },
  { "as_gl_window" , Fl_Lua_Choice_as_gl_window },
#if (FL_MAJOR_VERSION>=1 && FL_MINOR_VERSION>=3 && FL_PATCH_VERSION>=3)
  { "use_accents_menu", Fl_Lua_Choice_use_accents_menu },
#endif
  { "color2"       , Fl_Lua_Choice_color2     },
  { "__tostring"   , Fl_Lua_Choice___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


 int luaopen_FLTK_Fl_Choice(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "FLTK.Fl_Lua_Choice");
  // <mt>

  // register member methods
  dub::fregister(L, Fl_Lua_Choice_member_methods);
  // setup meta-table
  dub::setup(L, "FLTK.Fl_Lua_Choice");
  // <mt>
  return 1;
}
